#!/bin/sh

# Evaluaate differential interactions in the given directory, which
# was generated by conserved-roc.sh.
JOB_DIR=$1

# For each cell type, evaluate differential interactions.
DISCRETE_DATA_FILE=${JOB_DIR}/injected-discrete-3-9.csv
SIMULATED_INTERACTIONS_FILE=${JOB_DIR}/simint-injected.csv
for celltype in EB EE EC ISC ; do

    echo Evaluating differential interactions in $celltype

    # Subdirectory per celltype. This location is what
    # unique-interactions.r will create.
    SUB_JOB_DIR=${JOB_DIR}/work/${celltype}
    if [ ! -d ${SUB_JOB_DIR} ]; then
        rm -f ${SUB_JOB_DIR}
        mkdir -p ${SUB_JOB_DIR}
    fi

    # Build the per-interaction trajectory files.
    Rscript --no-restore ${PROJ_DIR}/r/unique-interactions.r $celltype ${DISCRETE_DATA_FILE}

    # Evaluate the differential interactions using GLN.
    for pmode in 3 5 ; do
        echo "  " Evaluating ${SUB_JOB_DIR} using -P ${pmode}
        OUT_FILE=${JOB_DIR}/${celltype}-P${pmode}.csv
        echo "    " Writing results to ${OUT_FILE}
        ./sh/cpx2-all.sh ${SUB_JOB_DIR} ${pmode} > $OUT_FILE
        echo rocPlot $OUT_FILE $SIMULATED_INTERACTIONS_FILE
        Rscript --no-restore ${PROJ_DIR}/r/rocPlot.r --from-table $OUT_FILE $SIMULATED_INTERACTIONS_FILE
        echo END rocPlot
        mv Rplots.pdf ${JOB_DIR}/ROC-${celltype}-${pmode}.pdf
    done

done

